swagger: '2.0'
info:
  version: 1.0.0
  title: iot-X RESFful API
  description: 'This project makes the deployment of IOT become more simple, more flexible, more powerful.It provides a full set of solutions from sensor to cloud server.'
host: localhost
paths:
  /device:
    get:
      description: 获取device对象列表
      parameters:
        - name: name
          in: query
          description: 通过设备名称过滤
          required: false
          type: string
        - name: namePartten
          in: query
          description: 通过设备名称的正则表达式过滤
          required: false
          type: string
        - name: state
          in: query
          description: 通过设备状态过滤
          required: false
          type: string
        - name: sortField
          in: query
          description: "指定返回列表排序的域，取值只能是\"name\"\\\"namePartten\"\\\"state\""
          required: false
          type: string
        - name: sortOrder
          in: query
          description: "指定返回列表是升序还是降序，取值只能是\"ASC\"\\\"DESC\""
          required: false
          type: string
        - name: numGet
          in: query
          description: 指定需要获取的设备个数
          required: false
          type: integer
        - name: numSkip
          in: query
          description: 指定需要跳过的设备个数
          required: false
          type: integer
      responses:
        '200':
          description: sucessful
          schema:
            title: respDevicelist
            type: array
            items:
              $ref: '#/definitions/respDeviceInfo'
        '400':
          description: parameter is not invalid
        '401':
          description: unauthorized
        '403':
          description: principal doesn't have permissions
        
definitions:
  respDeviceInfo:
    type: object
    properties:
      id:
        type: string
        description: 设备ID
      name:
        type: string
        description: 设备名称
      state:
        type: string
        description: 设备状态
      dataJason:
        type: string
        description: 设备数据，满足jason格式，由用户自己定义和解析，系统不感知
        
      
          
        
    
